[package]
name = "rusty-pine"
version = "0.1.0"
authors = ["Fabian Badoi <fb@penneo.com>"]
edition = "2018"

[dependencies]
log = "^0.4"
env_logger = "^0.6"
pest = "^2.1"
pest_derive = "^2.1"
regex = "^1.1"
mysql = "^16.0"

[[bin]]
name="analyze"
path="src/analyze.rs"
